apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfe-data-pvc
  namespace: terraform-enterprise
  labels:
    app: terraform-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
